####################################
# Project ConsoleEngine
#
# Auto generated via makeproj ver 1.2_beta
#  David Schoosleitner (c) 2022
####################################

### COMPILER DEFINITIONS ###

# Generated by C++ makeproj include
CXX := g++

# Generated by debug makeproj
GDB := gdb

### DIRECTORY DEFINITIONS ###

BUILD_DIR := 90_BUILD

# Generated by debug makeproj include
DEBUG_DIR := 90_BUILD/debug

SOURCE_DIR := 60_TESTING

### BUILD ARG DEFINITIONS ###

OUTPUT_FILE := ConsoleEngine

CCFLAGS := -Wno-literal-suffix -I./80_EXTERN/ -lX11 -lXtst

### SOURCE/OBJ DEFINITIONS ###

# Source Files, You may edit these to include files! 
SOURCES := main.cpp cutils.cpp

# Check if sources not empty
ifeq ($(SOURCES),)
$(error You forgot to include source files!)
endif

# Sources relocation into 70_DEV
SRC_DEV := $(SOURCES:%=$(SOURCE_DIR)/%)

# Objects relocation into 90_BUILD
OBJS := $(SOURCES:%=$(BUILD_DIR)/%.o)

# Generated by debug makeproj include
# Debug Objects relocation into 90_BUILD/debug
OBJ_DEBUG := $(SOURCES:%=$(DEBUG_DIR)/%.o)

### SCRIPTS ###

default: $(BUILD_DIR) $(OBJS)
	$(CXX) -o $(OUTPUT_FILE) $(OBJS) $(CCFLAGS) -DPRODUCTION_MODE=1

$(BUILD_DIR):
	mkdir $(BUILD_DIR)

# Generated by debug makeproj include
$(DEBUG_DIR): $(BUILD_DIR)
	mkdir $(DEBUG_DIR)

# Generated by debug makeproj include
debug: $(DEBUG_DIR) $(OBJ_DEBUG)
	$(CXX) -o $(OUTPUT_FILE)_gdb $(OBJ_DEBUG) $(CCFLAGS) -g

$(BUILD_DIR)/%.cpp.o: $(SOURCE_DIR)/%.cpp
	$(CXX) -o $@ -c $< $(CCFLAGS) -DPRODUCTION_MODE=1 

# Generated by debug makeproj include
$(DEBUG_DIR)/%.cpp.o: $(SOURCE_DIR)/%.cpp
	$(CXX) -o $@ -c $< $(CCFLAGS) -g

clean: $(BUILD_DIR)
	-@rm -r -f $(BUILD_DIR)/*
	-@rm -r -f $(OUTPUT_FILE)
	-@rm -r -f $(OUTPUT_FILE)_gdb
	@echo "Deleted $(BUILD_DIR) and $(OUTPUT_FILE)"

# Generated by run makeproj include
run: default
	./$(OUTPUT_FILE) $(args)

# Generated by run and debug makeproj include
rundebug: debug
	$(GDB) $(OUTPUT_FILE)_gdb
